[features]
seeds = false
skip-lint = false

[programs.localnet]
trading_program = "${PROGRAM_ID}"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "${SOLANA_CLUSTER_URL}"
wallet = "${SOLANA_WALLET_PATH}"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 